---
title: "R을 이용한 공공데이터 분석_제4장"
output:
  html_document:
    toc: true
    toc_float: true
    keep_md: true
date: '2022-06-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

제4장 데이터 내보내기 & 불러오기
-
```{r}
# 엑셀 데이터
no = c(1, 2, 3, 4, 5)
sex = c("male", "female", "male", "male", "female")
korean = c(87, 92, 95, 81, 87)

exam = data.frame(no, sex, korean)
exam


exam$no[1]
exam$sex[1]

# 데이터 타입
class(exam$sex)

exam$no
class(exam$no)

class(exam$korean)

str(exam)
```
# 1. 경로
```{r}
getwd()
#setwd()
?write.csv
write.csv(x = exam, file = "data/temp.csv") # 위에 만든 엑셀데이터 exam을 temp.csv를 만들어 적어라
```
- 바탕화면에 dataset 폴더 생성, exam 객체 저장하세요
- 데이터 불러오기
```{r}
temp = read.csv("data/temp.csv")
#temp = read.csv("dataset/temp.csv") 
#직전 상위 파일을 workdirectory로 지정하고 "폴더명/파일명"으로도 불러오기 가능
write.csv(x = exam, file = "data/exam.csv") #데이터프레임을 cvs파일로 저장
```
- R에서 예제파일 exam.csv를 객체 exam으로 입력해서 설명함. (51p)
```{r}
exam = read.csv("data/exam.csv") #csv파일을 데이터프레임으로 읽기
getwd()
?read.csv() #입력
```

```{r}
#install.packages("ggplot2")  #시각화 해주는 패키지
library(ggplot2)
economics <- ggplot2::economics
```

# 2. 외부 데이터 불러오기

- 여기서 잠깐 (66p)
- 실무 패키지 (분량이 많은 데이터를 불러올 때는 read.csv()보다 fread() 함수를 이용하는게 더 좋다.)
```{r}
#install.packages("data.table")
library(data.table)  #공식문서 확인
```

## 엑셀파일 불러오기

```{r}
#install.packages("readxl")
library(readxl)
read_excel("data/student1_xl.xlsx")
```

- (3) 설명 (67p)
```{r}
read.csv("data/student1.csv")
read.csv("data/student1.csv", skip = 1)
```

- (4) 설명_엑셀 파일에 있는 복수의 시트에서 특정시트 불러오기 (68p)
```{r}
read_excel("data/student1_xl.xlsx") # 첫번째 시트 불러오기
read_excel("data/student1_xl.xlsx", sheet =2) # 두번째 시트 불러오기
```
## txt파일 불러오기 (69p)

```{r}
#read.table()
```

## SPSS파일 불러오기 (73p)
```{r}
#install.packages("foreign")
library(foreign)
?read.spss()  #.sav 파일 읽어주는 함수
student <- read.spss("data/student.sav")
as.data.frame(student) #형변환 (리스트를 데이터프레임으로 변경)
```